### ISSUE TITLE
Add a way to pass in tag/version

### ISSUE THREAD

**Issue by waynebrantley** [sindresorhus/latest-version-cli#2]
Need to be able to do the equivalent 

``await latestVersion('npm', {version: 'latest-5'})``

**Comment by sindresorhus** [comment]
PR welcome

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/latest-version-cli/pull/3.

**Comment by LitoMore** [comment]
Sorry for the late response. I created a new PR and updated it.
