### ISSUE TITLE
Node 12 - Must use import to load ES Module

### ISSUE THREAD

**Issue by dptoot** [sindresorhus/latest-version-cli#6]
Thanks for the util!  Works perfectly on node 14.  Node 12 seems to throw the following error though

```
$ npx latest-version-cli react
npx: installed 103 in 6.296s
Must use import to load ES Module: C:\Users\jelewis1\AppData\Roaming\npm-cache\_npx\20228\node_modules\latest-version-cli\cli.js
```

It seems like node 12 is supported but it is using the node 14 ECMAScript module support?  Any advice  for those stuck on node 12 for now?

**Comment by dptoot** [comment]
I have answered my own question so feel free to close this if you like

```
npx -n=--experimental-modules latest-version-cli react
```

This is a little cumbersome but not the end of the world.  Perhaps a note in the README?

**Comment by sindresorhus** [comment]
Modules are supported since Node.js 12.

**Comment by dptoot** [comment]
Absolutely!  Its just that node 12 requires the experimental flag in order to use this as stated in the README.  Might be worth stating that this is required for node12 users in the doc but its easy enough for everyone to figure when they error out I suppose :)

Thanks for all the great work you do!
